// This was was generated
// DO NOT EDIT THIS FILE
//
// Unicode version: 10.0.0
// CLDR version: 32

package unicode

const (
	UpperHalfBlock = '▀' // 9600
	LowerOneEighthBlock = '▁' // 9601
	LowerOneQuarterBlock = '▂' // 9602
	LowerThreeEighthsBlock = '▃' // 9603
	LowerHalfBlock = '▄' // 9604
	LowerFiveEighthsBlock = '▅' // 9605
	LowerThreeQuartersBlock = '▆' // 9606
	LowerSevenEighthsBlock = '▇' // 9607
	FullBlock = '█' // 9608
	LeftSevenEighthsBlock = '▉' // 9609
	LeftThreeQuartersBlock = '▊' // 9610
	LeftFiveEighthsBlock = '▋' // 9611
	LeftHalfBlock = '▌' // 9612
	LeftThreeEighthsBlock = '▍' // 9613
	LeftOneQuarterBlock = '▎' // 9614
	LeftOneEighthBlock = '▏' // 9615
	RightHalfBlock = '▐' // 9616
	LightShade = '░' // 9617
	MediumShade = '▒' // 9618
	DarkShade = '▓' // 9619
	UpperOneEighthBlock = '▔' // 9620
	RightOneEighthBlock = '▕' // 9621
	QuadrantLowerLeft = '▖' // 9622
	QuadrantLowerRight = '▗' // 9623
	QuadrantUpperLeft = '▘' // 9624
	QuadrantUpperLeftAndLowerLeftAndLowerRight = '▙' // 9625
	QuadrantUpperLeftAndLowerRight = '▚' // 9626
	QuadrantUpperLeftAndUpperRightAndLowerLeft = '▛' // 9627
	QuadrantUpperLeftAndUpperRightAndLowerRight = '▜' // 9628
	QuadrantUpperRight = '▝' // 9629
	QuadrantUpperRightAndLowerLeft = '▞' // 9630
	QuadrantUpperRightAndLowerLeftAndLowerRight = '▟' // 9631

)
