// This was was generated
// DO NOT EDIT THIS FILE
//
// Unicode version: 10.0.0
// CLDR version: 32

package unicode

const (
	BlackSquare = '■' // 9632
	WhiteSquare = '□' // 9633
	WhiteSquareWithRoundedCorners = '▢' // 9634
	WhiteSquareContainingBlackSmallSquare = '▣' // 9635
	SquareWithHorizontalFill = '▤' // 9636
	SquareWithVerticalFill = '▥' // 9637
	SquareWithOrthogonalCrosshatchFill = '▦' // 9638
	SquareWithUpperLeftToLowerRightFill = '▧' // 9639
	SquareWithUpperRightToLowerLeftFill = '▨' // 9640
	SquareWithDiagonalCrosshatchFill = '▩' // 9641
	BlackSmallSquare = '▪' // 9642
	WhiteSmallSquare = '▫' // 9643
	BlackRectangle = '▬' // 9644
	WhiteRectangle = '▭' // 9645
	BlackVerticalRectangle = '▮' // 9646
	WhiteVerticalRectangle = '▯' // 9647
	BlackParallelogram = '▰' // 9648
	WhiteParallelogram = '▱' // 9649
	BlackUp_pointingTriangle = '▲' // 9650
	WhiteUp_pointingTriangle = '△' // 9651
	BlackUp_pointingSmallTriangle = '▴' // 9652
	WhiteUp_pointingSmallTriangle = '▵' // 9653
	BlackRight_pointingTriangle = '▶' // 9654
	WhiteRight_pointingTriangle = '▷' // 9655
	BlackRight_pointingSmallTriangle = '▸' // 9656
	WhiteRight_pointingSmallTriangle = '▹' // 9657
	BlackRight_pointingPointer = '►' // 9658
	WhiteRight_pointingPointer = '▻' // 9659
	BlackDown_pointingTriangle = '▼' // 9660
	WhiteDown_pointingTriangle = '▽' // 9661
	BlackDown_pointingSmallTriangle = '▾' // 9662
	WhiteDown_pointingSmallTriangle = '▿' // 9663
	BlackLeft_pointingTriangle = '◀' // 9664
	WhiteLeft_pointingTriangle = '◁' // 9665
	BlackLeft_pointingSmallTriangle = '◂' // 9666
	WhiteLeft_pointingSmallTriangle = '◃' // 9667
	BlackLeft_pointingPointer = '◄' // 9668
	WhiteLeft_pointingPointer = '◅' // 9669
	BlackDiamond = '◆' // 9670
	WhiteDiamond = '◇' // 9671
	WhiteDiamondContainingBlackSmallDiamond = '◈' // 9672
	Fisheye = '◉' // 9673
	Lozenge = '◊' // 9674
	WhiteCircle = '○' // 9675
	DottedCircle = '◌' // 9676
	CircleWithVerticalFill = '◍' // 9677
	Bullseye = '◎' // 9678
	BlackCircle = '●' // 9679
	CircleWithLeftHalfBlack = '◐' // 9680
	CircleWithRightHalfBlack = '◑' // 9681
	CircleWithLowerHalfBlack = '◒' // 9682
	CircleWithUpperHalfBlack = '◓' // 9683
	CircleWithUpperRightQuadrantBlack = '◔' // 9684
	CircleWithAllButUpperLeftQuadrantBlack = '◕' // 9685
	LeftHalfBlackCircle = '◖' // 9686
	RightHalfBlackCircle = '◗' // 9687
	InverseBullet = '◘' // 9688
	InverseWhiteCircle = '◙' // 9689
	UpperHalfInverseWhiteCircle = '◚' // 9690
	LowerHalfInverseWhiteCircle = '◛' // 9691
	UpperLeftQuadrantCircularArc = '◜' // 9692
	UpperRightQuadrantCircularArc = '◝' // 9693
	LowerRightQuadrantCircularArc = '◞' // 9694
	LowerLeftQuadrantCircularArc = '◟' // 9695
	UpperHalfCircle = '◠' // 9696
	LowerHalfCircle = '◡' // 9697
	BlackLowerRightTriangle = '◢' // 9698
	BlackLowerLeftTriangle = '◣' // 9699
	BlackUpperLeftTriangle = '◤' // 9700
	BlackUpperRightTriangle = '◥' // 9701
	WhiteBullet = '◦' // 9702
	SquareWithLeftHalfBlack = '◧' // 9703
	SquareWithRightHalfBlack = '◨' // 9704
	SquareWithUpperLeftDiagonalHalfBlack = '◩' // 9705
	SquareWithLowerRightDiagonalHalfBlack = '◪' // 9706
	WhiteSquareWithVerticalBisectingLine = '◫' // 9707
	WhiteUp_pointingTriangleWithDot = '◬' // 9708
	Up_pointingTriangleWithLeftHalfBlack = '◭' // 9709
	Up_pointingTriangleWithRightHalfBlack = '◮' // 9710
	LargeCircle = '◯' // 9711
	WhiteSquareWithUpperLeftQuadrant = '◰' // 9712
	WhiteSquareWithLowerLeftQuadrant = '◱' // 9713
	WhiteSquareWithLowerRightQuadrant = '◲' // 9714
	WhiteSquareWithUpperRightQuadrant = '◳' // 9715
	WhiteCircleWithUpperLeftQuadrant = '◴' // 9716
	WhiteCircleWithLowerLeftQuadrant = '◵' // 9717
	WhiteCircleWithLowerRightQuadrant = '◶' // 9718
	WhiteCircleWithUpperRightQuadrant = '◷' // 9719
	UpperLeftTriangle = '◸' // 9720
	UpperRightTriangle = '◹' // 9721
	LowerLeftTriangle = '◺' // 9722
	WhiteMediumSquare = '◻' // 9723
	BlackMediumSquare = '◼' // 9724
	WhiteMediumSmallSquare = '◽' // 9725
	BlackMediumSmallSquare = '◾' // 9726

)
